### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by jabdoa2** [PierreRust/apigpio#3]
We would like up use apigpio in https://github.com/missionpinball/mpf/ which heavily relies on asyncio to support the RPi as some kind of port extender. However, we need a convenient way for our users to install it. Can you upload it to pypi? We only need python 3+ (currently 3.4 to 3.6).

**Comment by PierreRust** [comment]
Yes that's certainly possible and should not take long.
However I must warn you that it's currently far from complete and not necessarily stable. It works well for my need but I don't anybody else has really used it.
Have you already tried to play with it yet ?

**Comment by jabdoa2** [comment]
Yes we played with it. First PR: https://github.com/PierreRust/apigpio/pull/4. Expect some more. We will probably have a few users since it is a cheap tool to interface SPI/I2C devices and to control servos.

**Comment by PierreRust** [comment]
Ok, great news :)
I'll check the PR. 
I'll probably work again on it if it has more users !

**Comment by jabdoa2** [comment]
First draft of our RPi pinball platform: https://github.com/missionpinball/mpf/pull/958/files

**Comment by PierreRust** [comment]
I had a look at your project, looks like a lot of fun ! 

apigpio is now published on pypi : https://pypi.python.org/pypi/apigpio/0.0.1

However, I have not checked yet if everything works well after pip install.

**Comment by jabdoa2** [comment]
Thanks. Did you upload it including all PRs merged?

**Comment by PierreRust** [comment]
No, I'll push an updated version with the PR.

**Comment by PierreRust** [comment]
The new 0.0.2 version, available on Pypi, contains all the pull-requests
